version: "3.7"

services:
  explorer-api:
    build:
      context: ./api
    ports:
      - "8081:80"
    volumes:
      - ./api/src:/app/src
#    hostname: explorer-api
#    networks:
#      - mynet

  explorer-client:
    build:
      context: ./client
    ports:
      - "8080:80"
    volumes:
      - ./client/src:/app/src
    depends_on:
      - explorer-api
#    networks:
#      - mynet

#networks:
#  mynet:
#    driver: bridge
